# Generated by Django 4.1.4 on 2023-02-07 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpostmodel',
            name='author',
            field=models.CharField(default='NNE', max_length=255),
        ),
    ]
